# docker-compose file for local development and testing with container image.
version: '3.2'
services:
  devserver: &devserver
    build:
      context: .
      dockerfile: compose/Dockerfile
    expose:
      - "8090"
    ports:
      - "8090:8080"
    depends_on:
      - "db"
      - "hydra"
    # For devserver, mount the local directory inside the container as a volume
    # to allow local changes to be reflected without having to re-build the
    # container.
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
    env_file:
      - compose/base.env
  tox:
    <<: *devserver
    entrypoint: ["tox"]
    command: []
    env_file:
      - compose/base.env
      - compose/tox.env
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: true
      - type: volume
        source: tox-data
        target: /tmp/tox-data
  migrate:
    <<: *devserver
    command: ["migrate"]
  shell:
    <<: *devserver
    command: ["shell"]
  db:
    image: postgres
    env_file:
      - compose/base.env
  hydra:
    image: oryd/hydra:v0.11.12-alpine
    entrypoint: ["/tmp/start-hydra.sh"]
    ports:
      - "4444:4444"
      - "4445:4445"
    env_file:
      - compose/hydra.env
    depends_on:
      - hydradb
    volumes:
      - "./compose/start-hydra.sh:/tmp/start-hydra.sh/:ro"
  hydradb:
    image: postgres
    env_file:
      - compose/hydra.env

volumes:
  # A persistent volume for tox to store its stuff. This allows caching of
  # virtualenvs between runs.
  tox-data:
